In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("All required libraries are imported successfully!!!!!")

All required libraries are imported successfully!!!!!

In [4]:
df = pd.read_csv('business_dataset.csv')
df.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    1000 non-null   object
 1   StockCode    1000 non-null   object
 2   Description  999 non-null    object
 3   Quantity     1000 non-null   int64
 4   InvoiceDate  1000 non-null   object
 5   UnitPrice    1000 non-null   float64
 6   CustomerID   999 non-null    float64
 7   Country      1000 non-null   object
dtypes: float64(2), int64(1), object(5)
memory usage: 62.6+ KB

In [6]:
df.shape

(1000, 8)

In [8]:
df.describe()

          Quantity    UnitPrice    CustomerID
count  1000.000000  1000.000000    999.000000
mean     12.785000     3.037110  16023.130130
std      38.423706     5.896942   1865.129933
min     -24.000000     0.000000  12431.000000
25%       2.000000     1.250000  14688.000000
50%       4.000000     2.100000  16210.000000
75%      12.000000     3.750000  17908.000000
max     600.000000   165.000000  18085.000000

In [9]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    1
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     1
Country        0
dtype: int64

In [10]:
df.dropna(inplace=True)
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [11]:
df.duplicated().sum()

23

In [12]:
df.drop_duplicates(inplace=True)

In [13]:
df.duplicated().sum()

0

In [17]:
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [18]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['Description'] = df['Description'].astype(str)
df.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom

In [19]:
df.to_csv("business_dataset_cleaned.csv", index=False)

In [24]:
df = pd.read_csv('business_dataset_cleaned.csv')

print(df.isnull().sum())
print('-'*40)
print(df.duplicated().sum())
print('-'*40)
print(df.dtypes)
print('-'*40)
print(df.shape)

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64
----------------------------------------
0
----------------------------------------
InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object
----------------------------------------
(976, 8)

In [25]:
df.describe()

         Quantity   UnitPrice    CustomerID
count  976.000000  976.000000    976.000000
mean    12.997951    3.048473  15980.289959
std     38.831391    5.965496   1864.742095
min    -24.000000    0.100000  12431.000000
25%      2.000000    1.250000  14307.000000
50%      4.000000    2.025000  16098.000000
75%     12.000000    3.750000  17897.000000
max    600.000000  165.000000  18085.000000

In [26]:
total_quantity = df['Quantity'].sum()
df['Revenue'] = df['Quantity'] * df['UnitPrice']
total_revenue = df['Revenue'].sum()
average_unit_price = df['UnitPrice'].mean()
total_transactions = df['InvoiceNo'].nunique()
unique_customers = df['CustomerID'].nunique()

In [28]:
KPI_summary = {
    "Total Quantity sold" : total_quantity,
    "Total Revenue" : total_revenue,
    "Average Unit Price" : average_unit_price,
    "Total Unique Transactions" : total_transactions,
    "Total Unique Customers" : unique_customers
}
for kpi, value in KPI_summary.items():
    print(kpi, ":", value)

Total Quantity sold : 12686
Total Revenue : 24409.35
Average Unit Price : 3.048473360655738
Total Unique Transactions : 65
Total Unique Customers : 48

In [29]:
pd.DataFrame([KPI_summary]).to_csv(
    "KPI_Summary.csv", index=False
)